apiVersion: v1
kind: Service
metadata:
  name: pubgredzone-static
spec:
  ports:
  - port: 8082
    protocol: TCP
    name: pubgredzone-static
  selector:
    app: pubgredzone-static
---
apiVersion: v1
kind: Service
metadata:
  name: pubgredzone-ocr
spec:
  ports:
  - port: 3001
    protocol: TCP
    name: pubgredzone-ocr
  selector:
    app: pubgredzone-ocr
---
apiVersion: v1
kind: Service
metadata:
  name: pubgredzone-app
spec:
  ports:
  - port: 3000
    protocol: TCP
    name: pubgredzone-app
  selector:
    app: pubgredzone-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pubgredzone-static
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pubgredzone-static
    spec:
      containers:
      - name: pubgredzone-static
        image: container-registry.dev.ibmesports.com/pubgredzone-static:$IMAGE_TAG
        imagePullPolicy: Always
        env:
        - name: NGINX_LISTEN
          value: "*:8082"
        ports:
        - containerPort: 8082
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pubgredzone-app
spec:
  template:
    metadata:
      labels:
        app: pubgredzone-app
    spec:
      containers:
        - name: pubgredzone-app
          image: container-registry.dev.ibmesports.com/pubgredzone-app:$IMAGE_TAG
          env:
          - name: token
            valueFrom:
              secretKeyRef:
                name: pubgredzone
                key: api-key
          - name: OCR_HOST
            value: pubgredzone.ibmesports.com
          ports:
            - containerPort: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pubgredzone-ocr
spec:
  template:
    metadata:
      labels:
        app: pubgredzone-ocr
    spec:
      containers:
        - name: pubgredzone-ocr
          image: container-registry.dev.ibmesports.com/pubgredzone-ocr:$IMAGE_TAG
          ports:
            - containerPort: 3001
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pubgredzone-ingress
spec:
  tls:
    - hosts: 
      - pubgred.zone
      secretName: pubgredzone
  rules:
  - host: pubgredzone.ibmesports.com
    http:
      paths:
      - path: /
        backend:
          serviceName: pubgredzone-static
          servicePort: 8082
      - path: /process_pubg
        backend:
          serviceName: pubgredzone-ocr
          servicePort: 3001
      - path: /current
        backend:
          serviceName: pubgredzone-app
          servicePort: 3000
      - path: /all
        backend:
          serviceName: pubgredzone-app
          servicePort: 3000
  - host: pubgred.zone
    http:
      paths:
      - path: /current
        backend:
          serviceName: pubgredzone-app
          servicePort: 3000
      - path: /
        backend:
          serviceName: pubgredzone-static
          servicePort: 8082
      - path: /all
        backend:
          serviceName: pubgredzone-app
          servicePort: 3000
  - host: rotisserie.tv
    http:
      paths:
      - path: /current
        backend:
          serviceName: pubgredzone-app
          servicePort: 3000
      - path: /
        backend:
          serviceName: pubgredzone-static
          servicePort: 8082
      - path: /all
        backend:
          serviceName: pubgredzone-app
          servicePort: 3000
