apiVersion: v1
kind: Service
metadata:
  name: rotisserie-static
spec:
  ports:
  - port: 8082
    protocol: TCP
    name: rotisserie-static
  selector:
    app: rotisserie-static
---
apiVersion: v1
kind: Service
metadata:
  name: rotisserie-ocr
spec:
  ports:
  - port: 3001
    protocol: TCP
    name: rotisserie-ocr
  selector:
    app: rotisserie-ocr
---
apiVersion: v1
kind: Service
metadata:
  name: rotisserie-app
spec:
  ports:
  - port: 3000
    protocol: TCP
    name: rotisserie-app
  selector:
    app: rotisserie-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rotisserie-static
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rotisserie-static
    spec:
      containers:
      - name: rotisserie-static
        image: container-registry.dev.ibmesports.com/rotisserie-static:$IMAGE_TAG
        imagePullPolicy: Always
        env:
        - name: NGINX_LISTEN
          value: "*:8082"
        ports:
        - containerPort: 8082
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rotisserie-app
spec:
  template:
    metadata:
      labels:
        app: rotisserie-app
    spec:
      containers:
        - name: rotisserie-app
          image: container-registry.dev.ibmesports.com/rotisserie-app:$IMAGE_TAG
          env:
          - name: token
            valueFrom:
              secretKeyRef:
                name: rotisserie
                key: api-key
          - name: clientID
            valueFrom:
              secretKeyRef:
                name: rotisserie
                key: clientID
          - name: OCR_HOST
            value: rotisserie.tv
          ports:
            - containerPort: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rotisserie-ocr
spec:
  template:
    metadata:
      labels:
        app: rotisserie-ocr
    spec:
      containers:
        - name: rotisserie-ocr
          image: container-registry.dev.ibmesports.com/rotisserie-ocr:$IMAGE_TAG
          ports:
            - containerPort: 3001
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rotisserie-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - secretName: rotisserie-tls
    hosts:
    - rotisserie.tv
  rules:
  - host: rotisserie.tv
    http:
      paths:
      - path: /current
        backend:
          serviceName: rotisserie-app
          servicePort: 3000
      - path: /
        backend:
          serviceName: rotisserie-static
          servicePort: 8082
      - path: /all
        backend:
          serviceName: rotisserie-app
          servicePort: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-lego
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-lego
    spec:
      containers:
      - name: kube-lego
        image: jetstack/kube-lego:0.1.5
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: LEGO_EMAIL
          valueFrom:
            configMapKeyRef:
              name: kube-lego
              key: lego.email
        - name: LEGO_URL
          valueFrom:
            configMapKeyRef:
              name: kube-lego
              key: lego.url
        - name: LEGO_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
